### PR TITLE
Gh issue 115

### LINKED ISSUE #115: Treatment variable factor levels not respected when using `add_total_group()`/`add_treat_grps()`
### Description
If a study has serious adverse events only in one treatment group (e.g. Placebo), there are problems to display "Verum", "Placebo" and Total at the same time. 

- If add_total_group  is left out, Placebo and Verum are displayed as defined in the factors,
- If add_total_group is included, the Verum column disappears.

### Steps to Reproduce (Bug Report Only)
library(tidyverse)
library(Tplyr)

test <- tibble(treatment = "Placebo",
	       relationship="Not related") %>% 
  mutate(treatment=factor(
    	  treatment, levels=c("Verum", "Placebo")),
        relationship=factor(
          relationship, levels=c("Not related","Possible","Unlikely","Any")
                            )
  )

tab <- tplyr_table(test, treatment) %>%
  add_layer(group_count(relationship))  %>% 
  add_total_group %>% 
  build()

**Expected behavior:** [What you expected to happen]
I would expect three columns:
var1_Verum 
var1_Placebo
var1_Total

**Actual behavior:** [What actually happened]
if add_total_group is left out I get the expected behaviour:
var1_Placebo
var1_Verum

if add_total_group is included I get only:
var1_Placebo
var1_Total

### Versions

You can get this information from executing `sessionInfo()`.
R version 4.1.1 (2021-08-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19043)

Matrix products: default

locale:
[1] LC_COLLATE=English_Switzerland.1252  LC_CTYPE=English_Switzerland.1252   
[3] LC_MONETARY=English_Switzerland.1252 LC_NUMERIC=C                        
[5] LC_TIME=English_Switzerland.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] forcats_0.5.2   stringr_1.4.1   dplyr_1.0.10    purrr_0.3.5     readr_2.1.3    
 [6] tidyr_1.2.1     tibble_3.1.8    ggplot2_3.3.6   tidyverse_1.3.2 Tplyr_0.4.4    
[11] magrittr_2.0.3 

loaded via a namespace (and not attached):
 [1] pillar_1.8.1        compiler_4.1.1      cellranger_1.1.0    dbplyr_2.2.1       
 [5] tools_4.1.1         lubridate_1.8.0     jsonlite_1.8.2      googledrive_2.0.0  
 [9] lifecycle_1.0.3     gargle_1.2.1        gtable_0.3.1        pkgconfig_2.0.3    
[13] rlang_1.0.6         reprex_2.0.2        DBI_1.1.3           cli_3.4.1          
[17] rstudioapi_0.14     haven_2.5.1         xml2_1.3.3          withr_2.5.0        
[21] httr_1.4.4          hms_1.1.2           generics_0.1.3      vctrs_0.4.2        
[25] fs_1.5.2            googlesheets4_1.0.1 grid_4.1.1          tidyselect_1.2.0   
[29] glue_1.6.2          R6_2.5.1            fansi_1.0.3         readxl_1.4.1       
[33] tzdb_0.3.0          modelr_0.1.9        ellipsis_0.3.2      backports_1.4.1    
[37] scales_1.2.1        rvest_1.0.3         assertthat_0.2.1    colorspace_2.0-3   
[41] utf8_1.2.2          stringi_1.7.6       munsell_0.5.0       broom_1.0.1        
[45] crayon_1.5.2

### PR DESCRIPTION
**Pull request by mstackhouse**
This should fix #115.

This required some restructuring of the function `treatment_group_build()`. I've rerun all tests (and corrected one that I verified), but for any snapshots please double check me to make sure nothing is failing. Also, since this happens before anything else in the build process, anything else you think we need to check? I just want to be cautious and cover our bases before we push this out.

### CODE REVIEW

**Comment by mstackhouse** [comment]
@elimillera ok I do see an issue. I could use your input here as well - the variable order of the output dataset changed with the way I implemented this - now it's always alphabetical, but before it would put your additional treatment groups last:

```r
tplyr_table(adsl, TRT01P) %>%  
  add_total_group() %>% 
  add_layer(
    group_count(RACE)
  ) %>% 
  build()

# A tibble: 3 × 7
  row_label1         var1_Placebo var1_Total `var1_Xanomeli…` `var1_Xanomeli…` ord_layer_index ord_layer_1
  <chr>              <chr>        <chr>      <chr>            <chr>                      <int>       <dbl>
1 AMERICAN INDIAN O… "  0 (  0.0… "  1 (  0… "  1 (  1.2%)"   "  0 (  0.0%)"                 1           1
2 BLACK OR AFRICAN … "  8 (  9.3… " 23 (  9… "  9 ( 10.7%)"   "  6 (  7.1%)"                 1           2
3 WHITE              " 78 ( 90.7… "230 ( 90… " 74 ( 88.1%)"   " 78 ( 92.9%)"                 1           3
```

The weird part to me is that the factor levels are in the order I'd want them?

```r
t <- tplyr_table(adsl, TRT01P) %>%  
  add_total_group() %>% 
  add_layer(
    group_count(RACE)
  ) 

t %>% 
  build()

levels(t$built_target$TRT01P)
[1] "Placebo"              "Xanomeline High Dose" "Xanomeline Low Dose"  "Total"
```

**Comment by elimillera** [comment]
Hey @mstackhouse I also remember that but I'm pulling Tplyr v0.4.4 and I'm getting the same result:
```
remotes::install_github("atorus-research/Tplyr", ref = "v0.4.4")
adsl <- safetyData::adam_adsl
library(Tplyr)

tplyr_table(adsl, TRT01P) %>%  
  add_total_group() %>% 
  add_layer(
    group_count(RACE)
  ) %>% 
  build()
# A tibble: 3 × 7
  row_label1                       var1_Placebo   var1_Total     `var1_Xanomeline High Dose` `var1_Xanomeline Low Dose` ord_layer_index ord_l…¹
  <chr>                            <chr>          <chr>          <chr>                       <chr>                                <int>   <dbl>
1 AMERICAN INDIAN OR ALASKA NATIVE "  0 (  0.0%)" "  1 (  0.4%)" "  1 (  1.2%)"              "  0 (  0.0%)"                           1       1
2 BLACK OR AFRICAN AMERICAN        "  8 (  9.3%)" " 23 (  9.1%)" "  9 ( 10.7%)"              "  6 (  7.1%)"                           1       2
3 WHITE                            " 78 ( 90.7%)" "230 ( 90.6%)" " 74 ( 88.1%)"              " 78 ( 92.9%)"                           1       3
# … with abbreviated variable name ¹​ord_layer_1
```
That makes me think this is a difference caused by a dependency. The issue arises from this line in count:
https://github.com/atorus-research/Tplyr/blob/c3881476bea05401abe74c4e19bdaaf275006438/R/count.R#L162
The `dplyr::do` isn't executing in the order of the variables but alphabetically. I'll dig in to see if its a change of dplyr or something

**Comment by mstackhouse** [comment]
Here's my SessionInfo():

```
R version 4.1.1 (2021-08-10)
Platform: aarch64-apple-darwin20 (64-bit)
Running under: macOS Monterey 12.6

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] rlang_1.0.6      forcats_0.5.2    stringr_1.4.1    dplyr_1.0.10     purrr_0.3.5      readr_2.1.3     
 [7] tidyr_1.2.1      tibble_3.1.8     ggplot2_3.3.5    tidyverse_1.3.2  Tplyr_1.0.2.9000 testthat_3.1.5  

loaded via a namespace (and not attached):
 [1] httr_1.4.2          pkgload_1.2.1       jsonlite_1.7.2      modelr_0.1.8        brio_1.1.2         
 [6] assertthat_0.2.1    diffobj_0.3.4       huxtable_5.4.0      googlesheets4_1.0.0 cellranger_1.1.0   
[11] remotes_2.4.0       sessioninfo_1.1.1   pillar_1.7.0        backports_1.2.1     glue_1.6.2         
[16] rvest_1.0.3         colorspace_2.0-2    pkgconfig_2.0.3     devtools_2.4.2      broom_1.0.1        
[21] haven_2.4.3         scales_1.1.1        processx_3.5.2      tzdb_0.1.2          googledrive_2.0.0  
[26] generics_0.1.3      usethis_2.0.1       ellipsis_0.3.2      cachem_1.0.6        withr_2.5.0        
[31] cli_3.4.1           magrittr_2.0.1      crayon_1.5.2        readxl_1.3.1        memoise_2.0.0      
[36] ps_1.6.0            fs_1.5.0            fansi_0.5.0         xml2_1.3.3          pkgbuild_1.2.0     
[41] tools_4.1.1         prettyunits_1.1.1   hms_1.1.2           gargle_1.2.0        lifecycle_1.0.3    
[46] pharmaRTF_0.1.3     munsell_0.5.0       reprex_2.0.1        callr_3.7.0         compiler_4.1.1     
[51] grid_4.1.1          rstudioapi_0.13     waldo_0.4.0         gtable_0.3.0        DBI_1.1.1          
[56] rematch2_2.1.2      R6_2.5.1            lubridate_1.8.0     knitr_1.34          fastmap_1.1.0      
[61] utf8_1.2.2          rprojroot_2.0.2     desc_1.3.0          stringi_1.7.4       Rcpp_1.0.7         
[66] vctrs_0.4.1         dbplyr_2.1.1        tidyselect_1.2.0    xfun_0.25  
```

Are you using the same version of dplyr? If `do()` is superceded I'm kind of surprised that it would have a breaking change like this? Unless it's like a dependency function of do().

After we merge this we gotta set up Tplyr to use renv for development - because the snapshots are infuriating.

**Comment by mstackhouse** [comment]
@elimillera I think we should merge this now that we verified it's _not_ an issue in deployment. For the refactor of the `dplyr::do()` line, we can make another issue and another PR. We'll just hold this in devel for a few more updates before we merge to main and can make it a 1.1 release.

**Review by elimillera — APPROVED** [review]

**Pull request merged**
