### PR TITLE
closes #99 closes #101 doc: fix typo in multiple files

### LINKED ISSUE #99: Typo in Vignette
### Prerequisites

For more information, see the `CONTRIBUTING` guide.

### Description

Typo in one of the links that point to a vignette, so the link doesn't work.  This can be seen in the screenshot below or on 
https://atorus-research.github.io/Tplyr/index.html
vignette_typo

**Expected behavior:** [What you expected to happen]
Link to lead to the vignette page

### Versions
You can get this information from executing `sessionInfo()`.

### LINKED ISSUE #101: Typo in `f_str()` documentation on valid variables
`f_str()` docs say 'variance' instead of 'var' for the variance summary in desc layers.

https://github.com/atorus-research/Tplyr/blob/03f7650d932fd2fb5b9609c77ac6b220c991a0c7/R/format.R#L83

### PR DESCRIPTION
**Pull request by sadchla-codes**
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)
- [x] I have read the **CONTRIBUTING** document.
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by mstackhouse** [comment]
@sadchla-codes  can you also pick up #101 ?

**Comment by sadchla-codes** [comment]
Sure!

**Comment by mstackhouse** [comment]
One more favor! Can you mark this as the development version by updating this version number to `1.0.1.9000`?

https://github.com/atorus-research/Tplyr/blob/eab14d696c25ecd11ed1fb68849c13a63fa78153/DESCRIPTION#L3

**Comment by sadchla-codes** [comment]
@mstackhouse you got it!

**Comment by sadchla-codes** [comment]
@mstackhouse All set!

**Review by mstackhouse — APPROVED** [review]

**Pull request merged**
