### PR TITLE
Fixes for wrong count denoms

### LINKED ISSUE #80: Distinct Percentages not working for total groups
### Prerequisites

For more information, see the `CONTRIBUTING` guide.

### Description

It looks like additional treatment groups aren't merging properly for denoms on the current devel branch

### Steps to Reproduce (Bug Report Only)

``` r
library(Tplyr)

adae <- haven::read_xpt(url("https://github.com/phuse-org/TestDataFactory/raw/main/Updated/TDF_ADaM/adae.xpt"))

t <- tplyr_table(adae, TRTA) %>%
  add_total_group() %>%
  add_treat_grps(
    "Dosed" = c("Xanomeline High Dose", "Xanomeline Low Dose")
  ) %>% 
  add_layer(
    group_count("Any Body System") %>%
      set_distinct_by(USUBJID)
  ) 

t %>%
  build() %>% 
  dplyr::select(var1_Placebo, var1_Total, var1_Dosed)
#> # A tibble: 1 × 3
#>   var1_Placebo    var1_Total      var1_Dosed     
#>   <chr>           <chr>           <chr>          
#> 1 "  69 (100.0%)" " 225 (  Inf%)" " 156 (  Inf%)"
```

<sup>Created on 2022-07-19 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Expected behavior:** [What you expected to happen]

Denoms shouldn't be inf - they should respect totals from the current treatment group's header N values:

```r
header_n(t)

# A tibble: 5 × 2
  TRTA                     n
  <fct>                <int>
1 Dosed                  890
2 Placebo                301
3 Total                 1191
4 Xanomeline High Dose   455
5 Xanomeline Low Dose    435
```
**Actual behavior:** [What actually happened]

Infs are presented instead

### Versions

You can get this information from executing `sessionInfo()`.

### PR DESCRIPTION
**Pull request by elimillera**
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] All new and existing tests passed.

This PR closes #80.

There were a couple of changes in `get_denom_total`, but the actual issue was in `process_count_denoms`. The fix was to reorder the `complete` and the `left_join`. What would happen is the distinct denoms would get calculated correctly, but then the complete would come by and turn all the distinct denoms to 0, by reordering them it fixes the issue.

I think the test that changed below was actually incorrect so we had a test for it but didn't notice that it wasn't calculating correctly.

### CODE REVIEW

**Review by mstackhouse — COMMENTED** [review]
Changes and test look good - but I'm going to do a bit more spot checking.

**Comment by mstackhouse** [comment]
Let's include a fix for #92 and then we can merge.

**Comment by elimillera** [comment]
> Let's include a fix for #92 and then we can merge.

@mstackhouse That is fixed.

**Review by mstackhouse — APPROVED** [review]

**Comment by mstackhouse** [comment]
There it is. Let's merge it!

**Pull request merged**
